### PR TITLE
Update to make more easily compilable

### PR DESCRIPTION
**Pull request by bundabrg**
Presently BossShopPro has lots of dependencies that are locally provided. This makes it hard to compile.

I've made the following changes:
  * Updated Lombok
  * Change all system deps to provided
  * All missing deps that do not have their own maven repo is provided by repo.worldguard.com.au (mine) now
  * Stub EpicSpawners and Kingdom as it has no public api jar available

This now means anyone can pull the repo and do a 'mvn clean install'.

### CODE REVIEW

**Comment by Blackixx** [comment]
Thank you very much for your support! Instead of directly merging this PR, I created a new branch within this repo and merged your fix/maven branch into the bossshoppro/bundabrg branch. This makes it easier for me to test your changes. Once tested, I will merge them into master.

**Comment by Blackixx** [comment]
Did you succeed when trying to build the project? I get the following message:
`Failure to find org.black_ixx:PlayerPoints:pom:2.1.4 in https://repo.glaremasters.me/repository/public/ was cached in the local repository, resolution will not be reattempted until the update interval of repo has elapsed or updates are forced`

It seems like the repo does no longer contain the PlayerPoints code. I am aware this PlayerPoints maven configuration was already there before and not touched by you, I am just wondering whether it worked for you.

**Comment by bundabrg** [comment]
That one must have been in my local .m2 cache. I've uploaded it to my repo so it should work now (mvn -U to force).  I'll rename my .m2 and try a build without a cache to doublecheck.

**Comment by Blackixx** [comment]
Somehow, still, multiple imports do not work for me. Interested in a short Discord/Skype chat? Then we can try to solve this if you got some time for that. Discord name: Logende#6369

**Comment by bundabrg** [comment]
Very interesting. I've sent a friend request. I renamed my .m2 and did a full 'mvn clean install' which worked fine by downloading everything. I also let intellij do its own imports which also worked.  I do tend to find maven has it's issues now and then though.

**Comment by bundabrg** [comment]
Might be worth creating a travis CI that does the build so you have an independent test of any PR's as well. I can grab a copy of what I use on another project I maintain (BetonQuest).

**Comment by bundabrg** [comment]
I've added a .travis.yml file to my branch.  I think that's all that's needed anyway to let github do the full build.

**Comment by bundabrg** [comment]
Here is the build done by github when I enable travis on my fork:
  https://travis-ci.com/github/bundabrg/BossShopPro/builds/159722572

**Pull request closed without merging**
